apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
    - name: temp-container
      image: busybox
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: mysql-storage
          mountPath: /mnt/data
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-backup-pvc
